CREATE TABLE IF NOT EXISTS companies (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_type        VARCHAR(20) NOT NULL DEFAULT 'partner' COMMENT 'mother or partner',
    partnerId           INT NOT NULL DEFAULT 0,
    departmentId        INT NOT NULL DEFAULT 0,
    roleId              INT NOT NULL DEFAULT 0,
    parentId            INT NOT NULL DEFAULT 0,
    branch_access_type  VARCHAR(255) NOT NULL DEFAULT '0',
    partner_access_type VARCHAR(255) NOT NULL DEFAULT '0',
    username            VARCHAR(90) NOT NULL,
    password            VARCHAR(160) NOT NULL,
    enabled             TINYINT(1) NOT NULL DEFAULT 1,
    status              TINYINT(1) NOT NULL DEFAULT 1,
    firstname           VARCHAR(200) NULL,
    lastname            VARCHAR(200) NULL,
    email               VARCHAR(300) NULL,
    phone               VARCHAR(200) NULL,
    company             VARCHAR(200) NULL,
    logo_icon           VARCHAR(255) NULL,
    logo_main           VARCHAR(255) NULL,
    contact_person_img  VARCHAR(255) NULL,
    contact_person_name VARCHAR(200) NULL,
    contact_person_phone VARCHAR(200) NULL,
    contact_person_alt_phone VARCHAR(200) NULL,
    contact_person_email VARCHAR(300) NULL,
    address             VARCHAR(500) NULL,
    notes               MEDIUMTEXT NULL,
    user_type           INT NOT NULL DEFAULT 1,
    created_at          DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at          DATETIME NULL DEFAULT NULL,
    avatar              VARCHAR(90) NULL,
    created_by          INT NULL,
    updated_by          INT NULL,
    last_login          TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_companies_username (username),
    KEY idx_companies_enabled (enabled),
    KEY idx_companies_status (status),
    KEY idx_companies_deleted (deleted_at),
    KEY idx_companies_parent (parentId),
    KEY idx_companies_type (company_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
