CREATE TABLE IF NOT EXISTS mycompany (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partnerId           INT NOT NULL DEFAULT 0,
    departmentId        INT NOT NULL DEFAULT 0,
    roleId              INT NOT NULL DEFAULT 0,
    parentId            INT NOT NULL DEFAULT 0,
    branch_access_type  VARCHAR(255) NOT NULL DEFAULT '0',
    partner_access_type VARCHAR(255) NOT NULL DEFAULT '0',
    username            VARCHAR(90) NOT NULL,
    password            VARCHAR(160) NOT NULL,
    enabled             TINYINT(1) NOT NULL DEFAULT 1,
    status              TINYINT(1) NOT NULL DEFAULT 1,
    firstname           VARCHAR(200) NULL,
    lastname            VARCHAR(200) NULL,
    email               VARCHAR(300) NULL,
    phone               VARCHAR(200) NULL,
    company             VARCHAR(200) NULL,
    address             VARCHAR(500) NULL,
    notes               MEDIUMTEXT NULL,
    user_type           INT NOT NULL DEFAULT 1,
    created_at          DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at          DATETIME NULL DEFAULT NULL,
    avatar              VARCHAR(90) NULL,
    created_by          INT NULL,
    updated_by          INT NULL,
    last_login          TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_mycompany_username (username),
    KEY idx_mycompany_enabled (enabled),
    KEY idx_mycompany_status (status),
    KEY idx_mycompany_deleted (deleted_at),
    KEY idx_mycompany_parent (parentId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
